package com.cloudspace.jindun.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cloudspace.jindun.dao.NoticeMessage;

import com.cloudspace.jindun.dao.NoticeMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noticeMessageDaoConfig;

    private final NoticeMessageDao noticeMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noticeMessageDaoConfig = daoConfigMap.get(NoticeMessageDao.class).clone();
        noticeMessageDaoConfig.initIdentityScope(type);

        noticeMessageDao = new NoticeMessageDao(noticeMessageDaoConfig, this);

        registerDao(NoticeMessage.class, noticeMessageDao);
    }
    
    public void clear() {
        noticeMessageDaoConfig.getIdentityScope().clear();
    }

    public NoticeMessageDao getNoticeMessageDao() {
        return noticeMessageDao;
    }

}
