package com.cloudspace.jindun.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTICE_MESSAGE.
 */
public class NoticeMessage {

    private Long id;
    private String userid;
    private String bigtypeid;
    private String typeid;
    private String title;
    private String icon;
    private String content;
    private String clickurl;
    private String extra;
    private String addtime;
    private String image;
    private String noticeid;
    private String actionuserid;
    private String nickname;
    private Integer readstatus;

    public NoticeMessage() {
    }

    public NoticeMessage(Long id) {
        this.id = id;
    }

    public NoticeMessage(Long id, String userid, String bigtypeid, String typeid, String title, String icon, String content, String clickurl, String extra, String addtime, String image, String noticeid, String actionuserid, String nickname, Integer readstatus) {
        this.id = id;
        this.userid = userid;
        this.bigtypeid = bigtypeid;
        this.typeid = typeid;
        this.title = title;
        this.icon = icon;
        this.content = content;
        this.clickurl = clickurl;
        this.extra = extra;
        this.addtime = addtime;
        this.image = image;
        this.noticeid = noticeid;
        this.actionuserid = actionuserid;
        this.nickname = nickname;
        this.readstatus = readstatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getBigtypeid() {
        return bigtypeid;
    }

    public void setBigtypeid(String bigtypeid) {
        this.bigtypeid = bigtypeid;
    }

    public String getTypeid() {
        return typeid;
    }

    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getClickurl() {
        return clickurl;
    }

    public void setClickurl(String clickurl) {
        this.clickurl = clickurl;
    }

    public String getExtra() {
        return extra;
    }

    public void setExtra(String extra) {
        this.extra = extra;
    }

    public String getAddtime() {
        return addtime;
    }

    public void setAddtime(String addtime) {
        this.addtime = addtime;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getNoticeid() {
        return noticeid;
    }

    public void setNoticeid(String noticeid) {
        this.noticeid = noticeid;
    }

    public String getActionuserid() {
        return actionuserid;
    }

    public void setActionuserid(String actionuserid) {
        this.actionuserid = actionuserid;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Integer getReadstatus() {
        return readstatus;
    }

    public void setReadstatus(Integer readstatus) {
        this.readstatus = readstatus;
    }

}
